const penDiameter = 10.5;
const magnetDiameter = 5.0;
const magnetHeight = 2.5;

const magneticPenHolder = Arc(magnetDiameter)
  .material('steel')
  .ez(magnetHeight)
  .fit((s) =>
    Arc(magnetDiameter + 2)
      .material('plastic')
      .ez(magnetHeight)
  )
  .at(yz)
  .align('z>')
  .fit(
    Arc(penDiameter)
      .material('plastic')
      .voidIn(offset(1))
      .ez(magnetDiameter + 2)
      .align('x<')
      .x(1)
  )
  .view()
  .stl('holder', drop('material:steel'));
