const Profile = (pitch = 1, depth = 4 / 3) =>
  Polygon(
    Point(0, depth / -2),
    Point(pitch / -2, depth / 2),
    Point(pitch / -2, depth),
    Point(pitch / 2, depth),
    Point(pitch / 2, depth / 2)
  );

Profile().view();

export const ScrewThreadSegment = (
  diameter,
  { pitch = 1, angle = 60 / 360, play = 0.1, turn = 'right' } = {}
) => {
  const depth = pitch / 2 / Math.tan(angle * Math.PI);
  return Profile(pitch, (pitch * 0.5) / Math.tan(angle * Math.PI))
    .y(diameter / -2)
    .ry(1 / 4)
    .loft(
      seq((t) => (s) => s.rz(t).z(pitch * t * 1.001), {
        from: -1,
        by: 1 / 32,
        to: 1,
      })
    )
    .scale(1, 1, turn === 'right' ? 1 : -1)
    .grow(-play)
    .removeSelfIntersections()
    .add(Arc(diameter - depth).ez(pitch, -pitch))
    .clip(Box(diameter * 2).ez(pitch / 2, pitch / -2))
    .align('z>');
};


export const ScrewThread = (
  diameter,
  height,
  { pitch = 1, angle = 60 / 360, play = 0.1, turn = 'right' } = {}
) =>
  ScrewThreadSegment(diameter, { pitch, angle, play, turn })
    .z(seq((a) => a, { from: 0, to: height, by: pitch }))
    .clip(Box(diameter * 2).ez(height / 2, height / -2))
    .align('z>');


export const NutThreadSegment = (
  diameter,
  {
    pitch = 1,
    thickness = pitch * 2,
    angle = 60 / 360,
    play = 0.1,
    lefthanded = false,
  } = {}
) => {
  const depth = pitch / 2 / Math.tan(angle * Math.PI);
  return ScrewThreadSegment(diameter, {
    pitch,
    angle,
    play: -play,
  }).cutFrom(
    Arc(diameter + thickness)
      .cut(Arc(diameter - depth))
      .ez(pitch)
  );
};


export const NutThread = (
  diameter,
  height,
  { pitch = 1, angle = 60 / 360, play = 0.1, turn = 'right' } = {}
) =>
  NutThreadSegment(diameter, { pitch, angle, play, turn })
    .z(seq((a) => a, { from: 0, to: height, by: pitch }))
    .clip(Box(diameter * 2).ez(height));
